export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const USER_LOADED = "USER_LOADED";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const UPDATE_PASSWORD = "UPDATE_PASSWORD";
export const REQUEST_RESTORE = "RESTORE_PASSWORD";
export const RESTORE_PASSWORD = "RESTORE_PASSWORD";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const MANAGE_ACCOUNT = "MANAGE_ACCOUNT";
export const ACTION_PENDING = "ACTION_PENDING";

export const COUNT_MUSEUMS = "COUNT_MUSEUMS";
export const WHERE_IS = "WHERE_IS";
export const TAKE_CITIES = "TAKE_CITIES";

export const UPDATE_SELECTED = "UPDATE_SELECTED";

export const LOAD_2_SHOW = "LOAD_2_SHOW";
export const LOAD_NEAR_2_SHOW = "LOAD_NEAR_2_SHOW";
export const SETUP_LOADED = "SETUP_LOADED";

export const LOADING_TRUE = "LOADING_TRUE";
export const LOADING_FALSE = "LOADING_FALSE";

export const FILTER_REDUX = "FILTER_REDUX";
export const FILTER_MONGO = "FILTER_MONGO";

export const LOAD_REVIEWS = "LOAD_REVIEWS";
export const SELECT_REVIEW_4_EDIT = "SELECT_REVIEW_4_EDIT";
export const CREATE_REVIEW = "CREATE_REVIEWS";
export const UPDATE_REVIEW = "UPDATE_REVIEWS";
export const DELETE_REVIEW = "DELETE_REVIEWS";
export const CLEAN_REVIEWS = "CLEAN_REVIEWS";
